max-ping = 100
repeats = 10
sources = [
    #["https://raw.githubusercontent.com/suprohub/rbox/refs/heads/main/result/best_subscribition_by_rbox.txt"],
    ["https://raw.githubusercontent.com/OP1MINEL/v2ray-configs2/refs/heads/main/All_Configs_Sub.txt"],
    ["https://raw.githubusercontent.com/barry-far/V2ray-Configs/refs/heads/main/All_Configs_Sub.txt"]
]